### PR TITLE
Add package-lock.json - Closes #1943

### LINKED ISSUE #1943: Put back package-lock.json to the project
### Description of the problem
There is no `package-lock.json`, `npm install` is being used.

### Suggested solution
Use `npm ci` for for faster, more reliable builds, see [documentation](https://docs.npmjs.com/cli/ci) and [announcement](https://blog.npmjs.org/post/171556855892/introducing-npm-ci-for-faster-more-reliable).

### PR DESCRIPTION
**Pull request by ghost**
### What issue have I solved?

#1943

### How have I implemented/fixed it?

Generate `package-lock.json` using `npm install`; remove it from `.gitignore` and `git add` it. 

### How has this been tested?

By running `npm ci`; should be reviewed by a developer.

### Review checklist
- The PR follows our [Test guide](/LiskHQ/lisk-hub/blob/development/docs/TEST_GUIDE.md)
- The PR follows our [CSS guide](/LiskHQ/lisk-hub/blob/development/docs/CSS_GUIDE.md)

### CODE REVIEW

**Comment by slaweet** [comment]
IMO there should be `.gitattributes` for `package-lock.json` 
https://medium.com/@clarkbw/managing-generated-files-in-github-1f1989c09dfd
https://medium.com/@pablorsk/be-a-git-ninja-the-gitattributes-file-e58c07c9e915

**Comment by fchavant** [comment]
@slaweet what do you want specifically? `merge=*`? `-diff`?

**Comment by slaweet** [comment]
I found out that ` .gitattributes` exist only today, so I don't have practical experience, but I would go with
```
package-lock.json -diff -merge
```

**Comment by yasharAyari** [comment]
It seems like a good idea @slaweet. Let's discuss it later.

**Review by yasharAyari — APPROVED** [review]
thank you @fchavant.

**Pull request merged**
