### PR TITLE
Correct LSK range on transaction page - Closes #4136

### LINKED ISSUE #4136: Signs on transactions page wrong
On transactions page these signs make no sense. It should be `-`. I also suggest to add LSK to make it more clear what those number indicate. Also the formatting looks not good. Should be aligned better in a clear way.

`      0 - 10 LSK`
`    10 - 100 LSK` 
`  100 - 1,000 LSK`
`1,000 - 10,000 LSK`

image

image

### PR DESCRIPTION
**Pull request by gadjacobs**
### What was the problem?

This PR resolves #4136 

### How was it solved?

- Updated the signs and ranges for transaction legends
- Added css for alignment fixes

### How was it tested?

Visually

### CODE REVIEW

**Review by ikem-legend — APPROVED** [review]

**Review by reyraa — CHANGES_REQUESTED** [review]
I still see the alignment issue. Also, try resizing the screen, the middle pie chart shrinks till it disappears, but the left one doesn't change. I think they should shrink equally, and if required, meaning there's no room to display both charts properly, we should break to the small-screen media query in a wider width.

**Review by ikem-legend — DISMISSED** [review]

**Review by reyraa — DISMISSED** [review]
Looks a lot better now.

**Comment by ann-vashchenko** [comment]
Hi, @eniolam1000752  could you move guides to the top, please? 
Screenshot 2022-02-21 at 11 41 28

**Review by ikem-legend — DISMISSED** [review]

**Review by reyraa — DISMISSED** [review]

**Review by ikem-legend — COMMENTED** [review]
Looks good generally asides a minor observation for the legend. The colour for the reclaim legend is missing or too similar to the background image

**Review by reyraa — APPROVED** [review]

**Review by ann-vashchenko — APPROVED** [review]

**Review by ikem-legend — APPROVED** [review]

**Review by reyraa — APPROVED** [review]

**Pull request merged**
