### PR TITLE
Fixed rerender issue on clicking entire balance warning - Closes #4176

### LINKED ISSUE #4176: Clicking on send entire balance warning causes a rerender
### Expected behavior

When the warning is clicked, nothing should happen.

### Actual behavior

Clicking anywhere on the warning causes a re-render.

### Steps to reproduce

- Go to any user account and try to send some LSK
- Click on 'send entire balance' on the send modal
- Now click on the warning that appears below the input field

### Which version(s) does this affect? (Environment, OS, etc...)
v2.3.0 beta.0

### PR DESCRIPTION
**Pull request by ikem-legend**
### What was the problem?

This PR resolves #4176

### How was it solved?

Changing the click setup for the warning

### How was it tested?

Manually

### CODE REVIEW

**Review by eniolam1000752 — COMMENTED** [review]
I think a unit test for this scenario would be needed.

**Comment by ikem-legend** [comment]
> I think a unit test for this scenario would be needed.

Fixed

**Review by eniolam1000752 — CHANGES_REQUESTED** [review]
There a commits from other branches that I think are not suppose to be in this PR

**Comment by ikem-legend** [comment]
> There a commits from other branches that I think are not suppose to be in this PR

Since the PR needed to be rebased from release, rather than development, some extra commits became part of it but I'll review them

**Comment by ikem-legend** [comment]
Similar PR https://github.com/LiskHQ/lisk-desktop/pull/4187 was created with cleaner history

**Pull request closed without merging**
