### PR TITLE
Fix translation on request modal & Show only QR code on other accounts - resolves #3009

### LINKED ISSUE #3009: Request LSK functionality is missing in the new layout.
Request LSK functionality is missing in the new layout. 

image

### Which version(s) does this affect? (Environment, OS, etc...)
1.27.0

### PR DESCRIPTION
**Pull request by isalga**
image
### What was the problem?
Translation where not properly passed to the Request component. Resolves issues with #3009 

### How was it solved?
Import and use withTranslation

### How was it tested?
Manual test

### CODE REVIEW

**Review by UsamaHameed — APPROVED** [review]

**Review by UsamaHameed — CHANGES_REQUESTED** [review]
We also need to show the sign in tooltip when the user is not logged in. @isalga @sridharmeganathan

**Review by reyraa — APPROVED** [review]
Looks good. Thanks

**Review by UsamaHameed — APPROVED** [review]

**Review by sridharmeganathan — CHANGES_REQUESTED** [review]
It is not working as expected and also without sign-in the functionality is not working.

**Review by sridharmeganathan — APPROVED** [review]
Functionality is working as expected

**Review by reyraa — APPROVED** [review]
Looks good. Thanks

**Pull request merged**
