### PR TITLE
Resolved issue with send tx from a multi-sig account

### LINKED ISSUE #4622: Unable to transfer token from multisignature account
### Expected behavior

- Users should be able to transfer token from multisignature account
- Downloaded file should have id, e.g `tx-3e78f02f31298c13053e818099b4e2ff2e085d9b15359a5b11720b2eff192a82.json`

### Actual behavior

There are two bugs in multisignature transaction:

- Unable to transfer token from multisignature account
- Missing transaction ID in multisignature transaction `tx-.json`

### Steps to reproduce

- Convert normal account to multisignature account
- Transfer token from converted multisignature account

### Which version(s) does this affect? (Environment, OS, etc...)
v3

### PR DESCRIPTION
**Pull request by eniolam1000752**
### What was the problem?

This PR resolves #4622, #4595

### How was it solved?

- [x] Resolve inability to sign send transaction from a multi signature account
- [x] Resolve wrong tx fee on send transaction from a multi signature account
- [x] Confirm and ensure delegate registration works

### How was it tested?

- Jest
- Visually

### CODE REVIEW

**Comment by ManuGowda** [comment]
@eniolam1000752 I am unable to register delegate from a multisignature account
Screenshot 2022-12-08 at 2 12 06 PM

Steps:

- Register multisignature account
- Register delegate from the upgraded multisignature account

**Review by ManuGowda — CHANGES_REQUESTED** [review]
@eniolam1000752 multisig registration is working.
delegate registration also works on regular account, but delegate registration on a multisig account stops at sign flow.

Also I see lot of TODOs can you please create a GitHub issue to address these TODOs

**Comment by ManuGowda** [comment]
- Information shown is incorrect (rank, last block forged, voters)
Screenshot 2022-12-08 at 2 20 25 PM

- Delegate is registered
Screenshot 2022-12-08 at 2 19 49 PM

- Delegates tab doesn't show my profile instead still shows `register delegate`
Screenshot 2022-12-08 at 2 19 38 PM

**Comment by eniolam1000752** [comment]
@ManuGowda I think the issue with the UI would be attended to by the validator tasks. I would align with @soroushm to see how these tasks can be modified

**Review by ManuGowda — APPROVED** [review]

**Review by ikem-legend — APPROVED** [review]

**Pull request merged**
