### PR TITLE
Add unit tests for voting queue components - Closes #3159

### LINKED ISSUE #3159: Transaction result modal does not display the vote amount properly
### Expected behavior
The display should match the prototype. 

### Actual behavior
It displays a bugged value. 

### Steps to reproduce
Unvote for more than once delegates.

### PR DESCRIPTION
**Pull request by UsamaHameed**
### What was the problem?
This PR resolves #3159

### How was it solved?
Increase test coverage and keeping state consistent. 

### How was it tested?
Unit and manual tests

### CODE REVIEW

**Comment by reyraa** [comment]
Cloud you please fix this icon too? It's too big.
Screenshot 2020-11-13 at 14 14 43

**Comment by UsamaHameed** [comment]
> Cloud you please fix this icon too? It's too big. It should match the icon on the header, just like they're one element and only change in color
> Screenshot 2020-11-13 at 14 14 43

I don't see this issue in my local. 🤔

**Comment by reyraa** [comment]
Chrome preserves the intrinsic dimensions but Firefox respects the Flex property. We run against Chrome, you can leave it as it is.

**Comment by UsamaHameed** [comment]
> Chrome preserves the intrinsic dimensions but Firefox respects the Flex property. We run against Chrome, you can leave it as it is.

I checked in firefox as well but didn't see the issue 🤔

**Review by reyraa — APPROVED** [review]

**Pull request merged**
