### PR TITLE
Run unit and E2E tests in parallel - Closes #1139

### LINKED ISSUE #1139: Setup parallel Jenkins stages for unit and e2e tests
### Expected behaviour
Should be possible to setup parallel stages reusing workspace folder and agent:
- https://issues.jenkins-ci.org/browse/JENKINS-46809
- https://issues.jenkins-ci.org/browse/JENKINS-47163

`stage ('Run Unit Tests')` and `stage ('Run E2E Tests')` should be able to run in parallel to speed up the build.

### Actual behaviour
Jenkins stages run serially.

### PR DESCRIPTION
**Pull request by ghost**
Depends on #1301.

### What issue have I solved?

- #1139 
### How have I implemented/fixed it?

Changed `Jenkinsfile` to run both mocha and jest unit tests as well as E2E tests in parallel.

### How has this been tested?

Build passes on [Jenkins](https://jenkins.lisk.io/job/lisk-hub/job/1139-paralell-unit-tests/), unit and E2E tests run in parallel; build take 4 minutes less.

### Review checklist
- The PR follows our [Test guide](/LiskHQ/lisk-hub/blob/development/docs/TEST_GUIDE.md)
- The PR follows our [CSS guide](/LiskHQ/lisk-hub/blob/development/docs/CSS_GUIDE.md)

### CODE REVIEW

**Comment by slaweet** [comment]
@fchavant I looks almost right now. The only problem I found is that the Slack notifications to `#lisk-ci-hub` on failure are not sent. 
I made some changes to make it fail on this run: https://jenkins.lisk.io/job/lisk-hub/job/PR-1303/24/ and nothing arrived to #lisk-ci-hub`

**Comment by fchavant** [comment]
@slaweet that's because we only send a slack notification on recovery (search for `liskSlackSend`) and not on error. This behaviour wasn't introduced in the PR but can found on the [1.5.0 branch](https://github.com/LiskHQ/lisk-hub/blob/1.5.0/Jenkinsfile) already.

**Comment by slaweet** [comment]
@fchavant https://github.com/LiskHQ/lisk-hub/pull/924/files is only chaging to use the definition of `fail` function from `@Library('lisk-jenkins')` but all other branches still send the fail notificaitons from inside `fail` function

**Comment by fchavant** [comment]
@slaweet you're right; I'll fix this PR then.

**Comment by fchavant** [comment]
Working now, see https://jenkins.lisk.io/job/lisk-hub/job/PR-1303/29/

**Review by slaweet — APPROVED** [review]
Now all tests passing and the build time is reduced from 16 to 11 mins. 🎉 That's great, thank you @fchavant

**Pull request merged**
