### PR TITLE
Add PR branch name to email notification subject when applicable - Closes #789

### LINKED ISSUE #789: Jenkins email notifications should include name of branch
### Expected behaviour
- Jenkins email notifications, as in slack integrations, should show branch name causing the event and not only PR number
### Actual behaviour
- Only PR number and link to jenkins is shown. 
### Steps to reproduce
- push some breaking changes to a branch.

### PR DESCRIPTION
**Pull request by ghost**
### What was the problem?
Email notification container PR number but not the branch name of the PR

### How did I fix it?
Added the PR branch name to the notification email subject when applicable

### How to test it?
Break the build of a PR and look at the email being sent by Jenkins: its subject line should contain the PR branch name.

### Review checklist
- The PR solves #789 
- The PR follows our [Test guide](/LiskHQ/lisk-hub/blob/development/docs/TEST_GUIDE.md)
- The PR follows our [CSS guide](/LiskHQ/lisk-hub/blob/development/docs/CSS_GUIDE.md)

### CODE REVIEW

**Comment by slaweet** [comment]
@fchavant you can reuse `build_info = get_build_info()`:
https://github.com/LiskHQ/lisk-hub/blob/0e3ad5227600c71f913a3bc1c1b66ac617ab89ef/Jenkinsfile#L1-L8

**Review by faival — DISMISSED** [review]
Nice @fchavant !

**Comment by fchavant** [comment]
@slaweet I am not sure it makes sense to use `build_info` in the subject:
> `Subject: Build #6 of <https://jenkins.lisk.io/job/lisk-hub/job/PR-790/4/|lisk-hub/PR-790> (789-mail-with-pr-name)`
What do you think?

**Review by slaweet — APPROVED** [review]
Ok, it's fine. Thank you @fchavant

**Pull request merged**
